### ISSUE TITLE
Implement DOMTokenList replace and supports

### ISSUE THREAD

**Issue by arlolra** [fgnass/domino#111]
https://dom.spec.whatwg.org/#domtokenlist

**Comment by ppKrauss** [comment]
... To start the job, a suggestion. The most important is `tokenlist.value` (*get* and *set*).

**Comment by cscott** [comment]
Didn't implement `DOMTokenList#supports()` because I couldn't find any specs which actually used it.  The primary use of `DOMTokenList` is `Element#classList`, and that gives a `TypeError` when `#supports()` is called:
```
el = document.createElement('div');
el.supports(' ')
TypeError: div attribute of <class> does not define any supported tokens
```
Reopen a new bug if there's a specific use case for `#supports()` you'd like implemented.
