### ISSUE TITLE
DOMTokenList add/remove: Do not throw a SyntaxError if class is `undefined`

### ISSUE THREAD

**Issue by florianmrz** [fgnass/domino#126]
As of right now, calling `.remove` or `.add` on a `DOMTokenList` with `undefined` will throw a SyntaxError, although it should not [according to the spec](https://dom.spec.whatwg.org/#dom-domtokenlist-add), only when the class string is empty or includes whitespaces.

https://github.com/fgnass/domino/blob/a886e56d4e3bd3afa267883d1777570c108c6e4b/lib/DOMTokenList.js#L79-L86

In my case this was making issues due to Angular Universal using this package to pre-render an application in NodeJS. The framework I'm using in a project is setting a class that is `undefined`, which isn't causing issues in a browser (no error is thrown and the call is ignored), but does while pre-rendering it via Universal.
Here's the original issue: https://github.com/sherweb/ngx-materialize/issues/329

Is this intended behaviour? If not, removing the check for `undefined` should resolve the issue.

Same goes for `DOMTokenList.contains`, as the same `handleErrors` function is run here.

**Comment by cscott** [comment]
Hm, the specified behavior is that the `null` or `undefined` is stringified to `"null"` or `"undefined"` and *that string* is added as a class.  The call isn't "ignored".

Oddly (?), `el.classList.add()` is handled differently than `el.classList.add(undefined)`.  The former is actually ignored, the latter is stringified.

I'm more inclined to fix the former case than the latter, as the domino behavior actually exposes otherwise-tricky-to-find bugs when you try to pass `null` or `undefined`.  I'm not sure that strict spec compliance is useful here.

**Comment by florianmrz** [comment]
That's correct, I wasn't aware that these value were actually stringified. Glad it's fixed now, thank you!
