### ISSUE TITLE
How to keep the encoded string in html ?

### ISSUE THREAD

**Issue by kuncevic** [fgnass/domino#157]
I have failed an issue on angular universal repo https://github.com/angular/universal/issues/1484 but it is turned out to be `domino's` default behavior.

Basically my issue that I have a use-case where I want to keep encoded string in my html.

as per this [comment](https://github.com/angular/universal/issues/1484#issuecomment-581812058) here is a current behavior, the string gets decoded  by `domino`:

```
const domino = require("domino");

const window = domino.createWindow('<body>&#097;</body>', '');
window.document.serialize(); 
// "<html><head></head><body>a</body></html>"
```

Do you have any ideas how to achieve that?

**Comment by cscott** [comment]
Nope, not possible under the official W3C spec:
https://html.spec.whatwg.org/#serialising-html-fragments

The text node does not contain entities.  You could try using a "style, script, xmp, iframe, noembed, noframes, or plaintext element" as the standard says.  But otherwise the DOM does not (by spec) represent entities as anything other than the character they represent.
